name: DevSecOps CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5
    - uses: sonarsource/sonarcloud-github-action@v5
      env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
                -Dsonar.organization=wiernerblut
                -Dsonar.projectKey=wiernerblut_devsecops-demo-app
   security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
